version: "3"
services:
  frontend:
    container_name: frontend
    build:
        context: ./frontend_react_app
        dockerfile: Dockerfile.prod
    ports:
        - 3000:80
    volumes: 
        - node_modules:/usr/src/app/node_modules
        # - ./frontend_react_app:/usr/src/app
    depends_on:
      - backend
    

  backend:
    restart: always
    container_name: backend
    build: 
        context: ./backend_flask_server
        dockerfile: Dockerfile.prod 
    # volumes:
    #   - ./backend_flask_server:/usr/src/app
    ports:
      - 8080:8080

volumes:
  node_modules:  